# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 811bb4df3709a792d94351644766da2e863e63b153907866102636e92a69f459f97a6ef505d1a935e186e6821281e71685e18564230a1788e993a7c0f56c8a62

test:
  secret_key_base: 7877a1277fdaecad01384ddb55de92201970ded235d88b32e84e47b52312fdc2fe08dd06fa8306df2b1c35b73b6ff6402290f282eee96c788c8f6d1cf7814b59

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
